"""Public keys trusted to sign releases.

Generated by `python tools/release.py --keygen`, which prints the public key
and writes the private half to a file outside this repository. Paste the
public key here and commit it - it is public by design.

Keep the old key alongside the new one when rotating, until every install
has picked up a release signed by the new key. Removing it early orphans any
copy that has not updated yet, and the only way back is a manual reinstall.

This list being empty means updates are disabled (see signing.verify), which
is the intended state for a source checkout that has never published.
"""

TRUSTED_PUBLIC_KEYS: list[str] = [
    "LgmYaoTTkP/yt3V1aQg+6xxzpwbqXP4PyDpAo7R5fx8=",
]
