// Default avatar gallery. Files live in public/avatars/, generated by
// tools/generate_avatars.py - keep this count in sync with that script's
// PALETTE length.
const AVATAR_COUNT = 12

export const AVATAR_GALLERY = Array.from(
  { length: AVATAR_COUNT },
  (_, i) => `/avatars/avatar-${String(i + 1).padStart(2, '0')}.svg`,
)
